version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3000"  # Map host port 3001 to container port 3000
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - BIGQUERY_DATASET=${BIGQUERY_DATASET}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    volumes:
      - ./google-credentials.json:/app/google-credentials.json:ro
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"